version: '2'

services:

  mysql:
    image: mysql:5.7.22
    restart: always
    env_file:
      - .env
    entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    ports:
          - "3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/:ro
  web:
    build: .
    command: bash -c "./start.sh"
    volumes:
      - .:/code
    ports:
      - "5001:5000"
    depends_on:
      - mysql
    env_file:
      - .env
